// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBujXgojwl3zBTpupz2x5Zi66xsZoVpuw4',
    appId: '1:1020174533137:web:2971cf3e72ce3958e4a7b0',
    messagingSenderId: '1020174533137',
    projectId: 'flutter-study-2d14c',
    authDomain: 'flutter-study-2d14c.firebaseapp.com',
    storageBucket: 'flutter-study-2d14c.appspot.com',
    measurementId: 'G-V5SBVTZ36R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbVndK064nkj70Zr-w2g8BJr6o_XEsRmU',
    appId: '1:1020174533137:android:ddeb989d1663fcbbe4a7b0',
    messagingSenderId: '1020174533137',
    projectId: 'flutter-study-2d14c',
    storageBucket: 'flutter-study-2d14c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4vzxrTW8-t3BqBhD7vkjWKbdX1LHa3xM',
    appId: '1:1020174533137:ios:c9a2cf93b4aa1164e4a7b0',
    messagingSenderId: '1020174533137',
    projectId: 'flutter-study-2d14c',
    storageBucket: 'flutter-study-2d14c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4vzxrTW8-t3BqBhD7vkjWKbdX1LHa3xM',
    appId: '1:1020174533137:ios:c9a2cf93b4aa1164e4a7b0',
    messagingSenderId: '1020174533137',
    projectId: 'flutter-study-2d14c',
    storageBucket: 'flutter-study-2d14c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBujXgojwl3zBTpupz2x5Zi66xsZoVpuw4',
    appId: '1:1020174533137:web:f43c9208c5b05d6ee4a7b0',
    messagingSenderId: '1020174533137',
    projectId: 'flutter-study-2d14c',
    authDomain: 'flutter-study-2d14c.firebaseapp.com',
    storageBucket: 'flutter-study-2d14c.appspot.com',
    measurementId: 'G-T1ZHW3F7DG',
  );
}
